### PR TITLE
Avoid torn state race condition in RuntimeImport.IsLazy

### LINKED ISSUE #108: random ArgumentNullException in VS MEF when using VS
It is a random problem reported by customers, and it has random stack in the product side (random place accessing MEF), but share the same stack similar to the one I pasted here.

After looking into the MEF code, I think it is a MEF code bug, independent to the composition.  The only explanation I can get is that the bug is inside RuntimeImport.IsLazy implementation.  It runs into a race condition, because Nullable<bool> is not thread safe.  When one thread computed the value and sets the value to true, in the split time, another thread can see the value has been set, and is false, which leads it to think valueFunction is null.

```
Microsoft.Requires.NotNull[T](T,String)
Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker,RuntimeImport,RuntimeExport,Func`3)
Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker,RuntimeImport)
Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.SatisfyImmediateImports()
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
System.Lazy`1.CreateValue()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
```

### PR DESCRIPTION
**Pull request by AArnott**
There seems to be a race condition due to a non-atomic pair of memory writes while we lazily compute the value for `RuntimeImport.IsLazy`. 

A few hypotheses to explain the race condition:

1. Consider the case of the CPU reordering field write instructions, [which is allowed on some architectures, but not AMD64](https://en.wikipedia.org/wiki/Memory_ordering#In_symmetric_multiprocessing_(SMP)_microprocessor_systems). So that hypothesis is dubious.
1. The fields `hasValue` and `value` inside the `Nullable<T>` type are laid out in that order. So after a method constructs a new `Nullable<T>` value, it copies it to the field location, setting `hasValue` *first*. Before it copies the second field of the struct, another thread copies the entire struct to its own local stack, which now observes torn state of `hasValue=true;value=false` since `value` has not yet been set to true by the original thread. This seems to me the most plausible hypothesis.
1. Cache lines across cores: the `value=false` was cached by the reading thread and `hasValue` was not, such that `hasValue=true` is observed as the current value, but the stale `value=false` value is read from the cache. 

Any of these *should* be fixed by this change.

(hopefully) fixes #108

### CODE REVIEW

File: src/Microsoft.VisualStudio.Composition/NullableBool.cs [hunk 1]
```diff
@@ -0,0 +1,62 @@
+﻿// Copyright (c) Microsoft. All rights reserved.
+
+namespace Microsoft.VisualStudio.Composition
+{
+    using System;
+
+    /// <summary>
+    /// A nullable boolean value with atomic reads and writes.
+    /// </summary>
```
Comment (drewnoakes) [inline src/Microsoft.VisualStudio.Composition/NullableBool.cs]: Future readers may appreciate a remark such as: `Nullable<bool>` is larger than the machine's word size and is subject to tearing, which can result in invalid state during data races.

Comment (AArnott) [reply src/Microsoft.VisualStudio.Composition/NullableBool.cs]: Done.
